// Regenerates src/sprites.ts from the Pixel Icon Library (HackerNoon) SVG
// source. opentui has no image renderer, so we rasterize the 24x24 icons to a
// pixel grid, downscale to 8x8, and emit "#"/"." rows the plugin renders
// with half-block characters (square pixels in a 2:1 terminal cell).
//
// Run with: node scripts/build-sprites.mjs
// Icons (CC/MIT, Pixel Icon Library by HackerNoon):
//   explore -> search.svg, scout -> eye.svg, general -> robot.svg,
//   plan -> clipboard.svg, fallback -> question.svg

import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const __dirname = dirname(fileURLToPath(import.meta.url))
const LIB = join(__dirname, "..", "node_modules", "@hackernoon", "pixel-icon-library", "icons", "SVG", "regular")

const ICONS = {
  explore: "search.svg",
  scout: "eye.svg",
  general: "robot.svg",
  plan: "clipboard.svg",
  fallback: "question.svg",
}

const SIZE = 24
const TARGET = 8

// --- shape extraction -----------------------------------------------------

function parsePath(d) {
  const subpaths = []
  const tokens = d.match(/[mMlLhHvVzZ]|-?\d+(?:\.\d+)?/g)
  let x = 0
  let y = 0
  let cur = null // current subpath vertices
  let cmd = ""
  const start = () => {
    if (cur && cur.length) subpaths.push(cur)
    cur = []
  }
  const push = (nx, ny) => {
    if (!cur.length || cur[cur.length - 1][0] !== nx || cur[cur.length - 1][1] !== ny) cur.push([nx, ny])
  }
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i]
    if (/^[mMlLhHvVzZ]$/.test(t)) {
      cmd = t
      continue
    }
    const n = Number(t)
    if (cmd === "M") {
      start(); x = n; y = Number(tokens[++i]); push(x, y)
    } else if (cmd === "m") {
      start(); x += n; y += Number(tokens[++i]); push(x, y)
    } else if (cmd === "L") {
      x = n; y = Number(tokens[++i]); push(x, y)
    } else if (cmd === "l") {
      x += n; y += Number(tokens[++i]); push(x, y)
    } else if (cmd === "H") {
      x = n; push(x, y)
    } else if (cmd === "h") {
      x += n; push(x, y)
    } else if (cmd === "V") {
      y = n; push(x, y)
    } else if (cmd === "v") {
      y += n; push(x, y)
    } else if (cmd === "z" || cmd === "Z") {
      // close: nothing to do, subpath already holds vertices
    }
  }
  if (cur && cur.length) subpaths.push(cur)
  return subpaths
}

function parsePolygon(points) {
  const nums = points.trim().split(/[\s,]+/).map(Number)
  const verts = []
  for (let i = 0; i + 1 < nums.length; i += 2) verts.push([nums[i], nums[i + 1]])
  return [verts]
}

// --- point in polygon (even-odd), ray to the left ------------------------

function inside(subpaths, px, py) {
  let crossings = 0
  for (const verts of subpaths) {
    for (let i = 0; i < verts.length; i++) {
      const [x1, y1] = verts[i]
      const [x2, y2] = verts[(i + 1) % verts.length]
      // skip horizontal edges; count vertical edges crossing the ray
      if (y1 === y2) continue
      const ymin = Math.min(y1, y2)
      const ymax = Math.max(y1, y2)
      if (py > ymin && py <= ymax && x1 < px) crossings++
    }
  }
  return crossings % 2 === 1
}

function rasterize(svg) {
  const grid = Array.from({ length: SIZE }, () => Array(SIZE).fill(false))
  const fillShape = (subpaths) => {
    for (let y = 0; y < SIZE; y++) {
      for (let x = 0; x < SIZE; x++) {
        if (inside(subpaths, x + 0.5, y + 0.5)) grid[y][x] = true
      }
    }
  }
  // rects
  for (const m of svg.matchAll(/<rect x="(-?\d+)" y="(-?\d+)" width="(\d+)" height="(\d+)"\/>/g)) {
    const [x, y, w, h] = [+m[1], +m[2], +m[3], +m[4]]
    for (let yy = y; yy < y + h; yy++) for (let xx = x; xx < x + w; xx++) grid[yy][xx] = true
  }
  // polygons
  for (const m of svg.matchAll(/<polygon points="([^"]+)"\/>/g)) fillShape(parsePolygon(m[1]))
  // paths
  for (const m of svg.matchAll(/<path d="([^"]+)"\/>/g)) fillShape(parsePath(m[1]))
  return grid
}

function downscale(grid) {
  const step = SIZE / TARGET
  const out = []
  for (let y = 0; y < TARGET; y++) {
    let row = ""
    for (let x = 0; x < TARGET; x++) {
      let on = false
      for (let dy = 0; dy < step; dy++)
        for (let dx = 0; dx < step; dx++) on ||= grid[y * step + dy][x * step + dx]
      row += on ? "#" : "."
    }
    out.push(row)
  }
  return out
}

const sprites = {}
for (const [name, file] of Object.entries(ICONS)) {
  const svg = readFileSync(join(LIB, file), "utf8")
  sprites[name] = downscale(rasterize(svg))
}

const header = `// Generated by scripts/build-sprites.mjs — do not edit by hand.
// Pixel-art sprites rasterized from the Pixel Icon Library (HackerNoon, MIT):
//   explore -> search, scout -> eye, general -> robot, plan -> clipboard,
//   fallback -> question. "#" = filled pixel, "." = transparent.
// Icons from Pixel Icon Library by HackerNoon (github.com/hackernoon/pixel-icon-library).
export const SPRITES: Record<string, string[]> = ${JSON.stringify(sprites, null, 2)}
`

writeFileSync(join(__dirname, "..", "src", "sprites.ts"), header)
for (const [name, rows] of Object.entries(sprites)) {
  console.log(`\n=== ${name} ===`)
  console.log(rows.join("\n"))
}
