// Generated by scripts/build-sprites.mjs — do not edit by hand.
// Pixel-art sprites rasterized from the Pixel Icon Library (HackerNoon, MIT):
//   explore -> search, scout -> eye, general -> robot, plan -> clipboard,
//   fallback -> question. "#" = filled pixel, "." = transparent.
// Icons from Pixel Icon Library by HackerNoon (github.com/hackernoon/pixel-icon-library).
export const SPRITES: Record<string, string[]> = {
  "explore": [
    ".####...",
    "######..",
    "##...##.",
    "##...##.",
    "##..###.",
    ".######.",
    "..######",
    "......##"
  ],
  "scout": [
    "........",
    "..####..",
    ".######.",
    "########",
    "########",
    ".######.",
    "..####..",
    "........"
  ],
  "general": [
    "........",
    "...##...",
    ".######.",
    "########",
    "########",
    "########",
    ".######.",
    "........"
  ],
  "plan": [
    "...##...",
    ".######.",
    ".######.",
    ".#....#.",
    ".#....#.",
    ".#....#.",
    ".#....#.",
    ".######."
  ],
  "fallback": [
    "........",
    "..####..",
    "..####..",
    "...###..",
    "...##...",
    "........",
    "...##...",
    "........"
  ]
}
